### PR TITLE
Make dieharder out-of-box buildable from fresh checkout

### PR DESCRIPTION
**Pull request by marcusmueller**
This is kind of a big one. I apologize.

I tried to make the build work reliably on multiple machines, directly from checkout.
At first, that was kind of problematic, because I kept running into remnants of pre-checked-in libtool/autotool artifacts.

After removing these, and requiring that I do an `autoreconf --install` after checkout, I can now build, from debian Jessie to Fedora 33.

Things I hope to achieve:

* rgb meeting spurious support requests: If I had a wild guess, a lot of these might actually be related to the libtool-added files that simply have changed and don't work the same on every platform. Since letting `autoreconf --install` add them after checkout doesn't take a lot of time, I consider the "clean source tree" approach a net benefit
* cleaning up autogen.sh (by convention, that really only does exactly that: generate the files that come from out-of-tree) by removing the call to ./configure
* re-establishing the ease of single-command build by adding a build.sh
* making dieharder build on my machines
  * aside from the debian-supplied libdieharder.h `<stdint.h>` patch, this also requires complete removal of the unused `rgb_operm` from all Makefiles
  * `inline` symbols should usually be static, modern compilers will elsewise export the symbol, and subsequentially fail to find an implementation
  * Linking the final libdieharder.la simply wouldn't work without `-fcommon`, so adding that to the compiler flags
* general cleanliness of tree

### CODE REVIEW

**Comment by ffontaine** [comment]
@eddelbuettel, I think that https://github.com/eddelbuettel/dieharder/pull/2/commits/40d377b86c856f5a4510a6f5cd56be004873ad77 should be merged. We have applied this patch on buildroot since https://git.buildroot.net/buildroot/commit/?id=d0ffdb2bdd22432f6f269a43ceaf7f1e51d535b5.

**Comment by eddelbuettel** [comment]
I apologize for letting this PR slip but it is now stale / conflicting,  Would you mind extracting the relevant commit and make a new PR?  I should probably close this one.

(My notification settings for this repo were, for some reason, set to 'participate only' so I was set to not receive notification,. I changed that now.  Thanks for all your contributions here.)

**Comment by ffontaine** [comment]
OK, I'll send a separate PR

**Comment by ffontaine** [comment]
See #10, I would suggest to tag a new release after this one is merged.

**Comment by eddelbuettel** [comment]
Yes, absolutely, that is my plan too. I'll also add (belatedly) some minimal CI, maybe just after.  And will make a new Debian release with the same tag.

**Comment by eddelbuettel** [comment]
Now closing this PR (in favour of #10) with apologies for letting it bit-rot.

**Pull request closed without merging**
