### PR TITLE
Sync commits with dieharder-rgb repo

### LINKED ISSUE #17: Changes to dieharder-rgb git?
Hi,
this is more question than an issue...

I tried to follow history of tests added/changed in Dieharder and found these commits in dieharder-rgb that are not part of this repo (commit list is not complete, just examples):

- Updated Fill Tree 2 target...
https://github.com/eddelbuettel/dieharder-rgb/commit/67c2cb9a468c73014886f20c22af12c5162aab9c

- Added OPSO2 test
https://github.com/eddelbuettel/dieharder-rgb/commit/db68bb7db56dac25a12e287c41fe80a3f7c00a5e

- Added Birthday Spacing test variant
https://github.com/eddelbuettel/dieharder-rgb/commit/afee5533ee434cf9ba12f22735d8bcfd4adb3dfd

What's the story behind these changes? Any reason is is not part of current  (this) Dieharder repository? Does the repo just diverged?

Thanks!

### PR DESCRIPTION
**Pull request by mbroz**
As discussed i #17, these are missing committs from https://github.com/eddelbuettel/dieharder-rgb, changes by David Bauer.

Only trivial editing for clean patch apply (some build and warning fixes since that time), otherwise it shoudl be exact commits. (Other commits in log do not patch files present in this repo.)

I only quickly tested new tests 210, 211 (210 looks suspicious as it returns WEAK for /dev/urandom data... also the name is duplicate with test 0 - but this should be fixed later - rename to v2?)

Fixes: #17

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Hm. #16 appears to have brought us into this century by adding CI which apparently worked at the time.  Any idea what is wrong now?  Changed autotools conventions maybe?

**Comment by mbroz** [comment]
I do not think CI actually worked :-) It is "make distcheck" that requires some legacy svn thing, I would disable it for now (I'll try to do new commit once I can test it on my GitHub clone).

**Comment by eddelbuettel** [comment]
Agreed.  I should at least take out `make distcheck`.

Do you think it is worth me doing a real quick commit and you then rebased off that?

**Comment by mbroz** [comment]
I proposed PR #19 in the meantime.

**Comment by mbroz** [comment]
(Rebased over PR #19, so merge this one first if it is ok. thx )

**Comment by eddelbuettel** [comment]
That works but we now have 
> This branch is [8 commits ahead of](https://github.com/mbroz/dieharder/compare/eddelbuettel%3Adieharder%3Amaster...sync-rgb), [1 commit behind](https://github.com/mbroz/dieharder/compare/sync-rgb...eddelbuettel%3Adieharder%3Amaster) eddelbuettel/dieharder:master.

I could squash-merge for ease of it all.

**Review by eddelbuettel — APPROVED** [review]
Thanks for carrying these over from the other repo.

**Comment by mbroz** [comment]
Hm ,  seems I forgt to sync my master branch. Should be ok now.

**Comment by eddelbuettel** [comment]
My head is a little fried but I think my act of merging constitutes a change you could not have anticipated so you always needed to rebase relative to my master.  I may be wrong. 

But we're good so double-thanks.  Will merge this as is as it is thing of careful beauty.

**Pull request merged**
